title: 程序员老庹的重启手记
subtitle: '十年一梦，却道天凉好个秋'
description: '一个47岁老兵的技术与创业复盘'
keywords:
author: 程序员老庹
language: zh-CN
timezone: 'Asia/Shanghai'
url: http://laotuo.top # 请替换成你未来的域名
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  i_p: index.html
source_dir: source
public_dir: public
theme: landscape # 默认主题，后续可更换
deploy:
